### ISSUE TITLE
Code snippets 

### ISSUE THREAD

**Issue by Rowadz** [ninest/unique-code#2]
@ninest I really like this tool :) and I use it usually 

I have a suggestion if you don't mind me asking 

today I tried to put a code snippet into the input 

```js
export const fetchQuestionDetails = createAsyncThunk(
  'editor/fetchQuestionDetails',
  async ({ componentId }) => {
    return (await axios.get(...)).data
  }
)
```

output 

```
E᙭ᑭOᖇT ᑕOᑎᔕT ᖴETᑕᕼᑫᑌEᔕTIOᑎᗪETᗩIᒪᔕ = ᑕᖇEᗩTEᗩᔕYᑎᑕTᕼᑌᑎK( 'EᗪITOᖇ/ᖴETᑕᕼᑫᑌEᔕTIOᑎᗪETᗩIᒪᔕ', ᗩᔕYᑎᑕ ({ ᑕOᗰᑭOᑎEᑎTIᗪ }) => { ᖇETᑌᖇᑎ (ᗩᗯᗩIT ᗩ᙭IOᔕ.GET(...)).ᗪᗩTᗩ } )
```

so as a suggestion can you save the whitespaces or `\t` - `\r` -  `\n` you know, to change just the character and not the format

**Comment by ninest** [comment]
Thank you, I'm, very glad to hear that!

There are three changes I made:
1. Use a `textarea` instead of an `input`. You can now paste multiline text
2. Replacing newlines with `<br />`
3. Using `white-space: pre-wrap` and `overflow-wrap: break-word` on the text (Tailwind classes `whitespace-pre-wrap break-words`)

So pasting your code in the textarea returns

```js
// Bubble
E᙭ᑭOᖇT ᑕOᑎᔕT ᖴETᑕᕼᑫᑌEᔕTIOᑎᗪETᗩIᒪᔕ = ᑕᖇEᗩTEᗩᔕYᑎᑕTᕼᑌᑎK(
  'EᗪITOᖇ/ᖴETᑕᕼᑫᑌEᔕTIOᑎᗪETᗩIᒪᔕ',
  ᗩᔕYᑎᑕ ({ ᑕOᗰᑭOᑎEᑎTIᗪ }) => {
    ᖇETᑌᖇᑎ (ᗩᗯᗩIT ᗩ᙭IOᔕ.GET(...)).ᗪᗩTᗩ
  }
)
```

or

```ts
// Redact
██████ █████ ████████████████████ █ █████████████████
  ██████████████████████████████
  █████ ██ ███████████ ██ ██ █
    ██████ ██████ ████████████████████
  █
█
```

Try it out!

You'll notice that the upside down text doesn't preserve the spaces/tabs. It actually is, but it's difficult to see because they're at the right side of the sentence

**Comment by Rowadz** [comment]
oooh cool 

thanks!  <img src="https://cultofthepartyparrot.com/parrots/hd/thumbsupparrot.gif"  width="20" />  I appreciate it


```js
E᙭ᑭOᖇT ᑕOᑎᔕT ᖴETᑕᕼᑫᑌEᔕTIOᑎᗪETᗩIᒪᔕ = ᑕᖇEᗩTEᗩᔕYᑎᑕTᕼᑌᑎK(
  'EᗪITOᖇ/ᖴETᑕᕼᑫᑌEᔕTIOᑎᗪETᗩIᒪᔕ',
  ᗩᔕYᑎᑕ ({ ᑕOᗰᑭOᑎEᑎTIᗪ }) => {
    ᖇETᑌᖇᑎ (ᗩᗯᗩIT ᗩ᙭IOᔕ.GET(...)).ᗪᗩTᗩ
  }
)
```

```js
eXPoRT coNst FetchqUEstiOnDetaIls = CrEAteaSyNcThUNk(
  'eDitOr/fetcHquEstIoNDETaIls',
  asYnC ({ coMpONeNTid }) => {
    reTuRN (aWAIt AXios.geT(...)).data
  }
)
```
